Calculate Mean, Median, Mode, Variance, Standard Deviation

In [1]:
# Question 1
import statistics

numbers = [10, 20, 20, 30, 40, 50]

mean_value = statistics.mean(numbers)
median_value = statistics.median(numbers)
mode_value = statistics.mode(numbers)
variance_value = statistics.variance(numbers)
std_deviation = statistics.stdev(numbers)

print("Mean:", mean_value)
print("Median:", median_value)
print("Mode:", mode_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation)

Mean: 28.333333333333332
Median: 25.0
Mode: 20
Variance: 216.66666666666666
Standard Deviation: 14.719601443879744


2. Create a NumPy array and perform the following operations:

In [2]:
# Question 2
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("Array:", arr)

# Sum and Mean
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))

# Max and Min
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

# Reshape
reshaped_arr = arr.reshape(2,3)
print("Reshaped Array:\n", reshaped_arr)

# Element-wise multiplication
result = arr * 2
print("Element-wise multiplication:", result)

Array: [1 2 3 4 5 6]
Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Element-wise multiplication: [ 2  4  6  8 10 12]


Write a Python program to:
•	Create two matrices
•	Perform addition and subtraction
•	Perform matrix multiplication
•	Find transpose of a matrix


In [3]:
# Question 3
import numpy as np

matrix1 = np.array([[1,2,3],
                    [4,5,6]])

matrix2 = np.array([[7,8,9],
                    [1,2,3]])

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)

# Addition
print("Addition:\n", matrix1 + matrix2)

# Subtraction
print("Subtraction:\n", matrix1 - matrix2)

# Matrix Multiplication
matrix3 = np.array([[1,2],
                    [3,4],
                    [5,6]])

multiplication = np.dot(matrix1, matrix3)
print("Matrix Multiplication:\n", multiplication)

# Transpose
print("Transpose of Matrix1:\n", matrix1.T)

Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[7 8 9]
 [1 2 3]]
Addition:
 [[ 8 10 12]
 [ 5  7  9]]
Subtraction:
 [[-6 -6 -6]
 [ 3  3  3]]
Matrix Multiplication:
 [[22 28]
 [49 64]]
Transpose of Matrix1:
 [[1 4]
 [2 5]
 [3 6]]


Generate a random array of 10 numbers and calculate:
•	Mean
•	Standard deviation
•	Minimum and Maximum value


In [4]:
# Question 4
import numpy as np

random_array = np.random.rand(10)

print("Random Array:", random_array)

print("Mean:", np.mean(random_array))
print("Standard Deviation:", np.std(random_array))
print("Minimum:", np.min(random_array))
print("Maximum:", np.max(random_array))

Random Array: [0.45201543 0.30738165 0.84162467 0.04121483 0.2300375  0.05274442
 0.21790485 0.21056967 0.39082596 0.15340117]
Mean: 0.28977201205979114
Standard Deviation: 0.222025258604294
Minimum: 0.04121482767687401
Maximum: 0.841624667128013


Write a Python program using SciPy to:
•	Calculate mean using scipy.stats
•	Perform a t-test on a sample dataset


In [5]:
# Question 5
import numpy as np
from scipy import stats

data = np.array([10, 12, 9, 11, 10, 13, 12])

# Mean using scipy
mean_value = stats.tmean(data)
print("Mean using scipy:", mean_value)

# One sample t-test
t_statistic, p_value = stats.ttest_1samp(data, 10)

print("T-Statistic:", t_statistic)
print("P-Value:", p_value)

Mean using scipy: 11.0
T-Statistic: 1.8708286933869707
P-Value: 0.1105517404022668


. Write a Python program to compute definite integration of a mathematical function using scipy.integrate.

In [6]:
# Question 6
from scipy import integrate
import numpy as np

# Function definition
def func(x):
    return x**2

# Definite integration from 0 to 3
result, error = integrate.quad(func, 0, 3)

print("Integration Result:", result)
print("Estimated Error:", error)

Integration Result: 9.000000000000002
Estimated Error: 9.992007221626411e-14


Write a Python program to minimize a mathematical function using scipy.optimize.



In [7]:
# Question 7
from scipy.optimize import minimize

# Function to minimize
def func(x):
    return x**2 + 4*x + 4

initial_guess = 0

result = minimize(func, initial_guess)

print("Minimum Value:", result.fun)
print("Minimum at x =", result.x)

Minimum Value: 0.0
Minimum at x = [-2.00000002]
